version: 0.0
os: linux
files:
  - source: /student.war
#     destination: /var/lib/tomcat8/webapps/
    destination: /opt/tomcat/webapps/
hooks:
  BeforeInstall:
    - location: dependencies.sh
      timeout: 100
  AfterInstall:
    - location: afterinstall.sh
      timeout: 100
  ApplicationStart:
    - location: start_application.sh
      timeout: 100
