version: 0.0
os: linux
files:
  - source: /student.war
    destination: /var/lib/tomcat9/webapps/
hooks:
  AfterInstall:
    - location: afterinstall.sh
      timeout: 100
  ApplicationStart:
    - location: applicationstart.sh
      timeout: 100